# Generated by Django 3.0.7 on 2020-06-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mobile_spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_pic', models.ImageField(upload_to='mobiles/pics')),
                ('model', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('discription', models.CharField(max_length=250)),
            ],
        ),
    ]
