# Generated by Django 3.0.7 on 2020-06-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_buy_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_now',
            name='cart_models',
            field=models.ManyToManyField(to='home.mobile_spec'),
        ),
    ]
