# Generated by Django 3.0.7 on 2020-06-30 14:24

from django.db import migrations


class Migration(migrations.Migration):


    dependencies = [
        ('home', '0006_auto_20200630_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buy_mobile',
        ),
    ]
