# Generated by Django 3.0.7 on 2020-06-30 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_buy_mobiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buy_mobiles',
        ),
    ]
