# Generated by Django 3.0.7 on 2020-06-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_buy_mobiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_mobiles',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
