# Generated by Django 3.0.7 on 2020-06-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200630_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_mobiles',
            name='address',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
